# Generated by Django 3.0.2 on 2022-11-02 05:26

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo')),
                ('cedula', models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[1-9][0-9]{6,30}$'), 'No valida', 'invalid')])),
                ('celular', models.CharField(max_length=40, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[1-9][0-9]{5,30}$'), 'No valida', 'invalid')])),
                ('contacto', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nombre_usuario', models.CharField(max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('ultima_conexicon', models.DateTimeField(auto_now_add=True)),
                ('nacimiento', models.DateField(blank=True, null=True, verbose_name='Cumpleaños')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_perfil/')),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre', 'apellidos'],
            },
        ),
    ]
