# Generated by Django 3.2.16 on 2023-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20221228_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(choices=[('Profesor', 'PROFESOR'), ('Director', 'DIRECTOR'), ('Administrador', 'ADMINISTRADOR PLATAFORMA hacktathon_tech')], max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
