# Generated by Django 3.2.16 on 2024-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_tipousuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(choices=[('Profesor', 'PROFESOR'), ('Director', 'DIRECTOR'), ('Administrador', 'ADMINISTRADOR PLATAFORMA dashboard udec')], max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
