# Generated by Django 3.2.16 on 2024-10-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_tipousuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(choices=[('USUARIO', 'USUARIO'), ('COORDINADOR', 'COORDINADOR'), ('ADMINISTRADOR_SISTEMA', 'ADMINISTRADOR SISTEMA')], max_length=200, null=True, verbose_name='nombre'),
        ),
    ]
